/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/p-ai_edit`; params?: Router.UnknownInputParams; } | { pathname: `/p-import`; params?: Router.UnknownInputParams; } | { pathname: `/p-photo_detail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/p-album_home` | `/p-album_home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/p-group_manage` | `/p-group_manage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/p-settings` | `/p-settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/p-ai_edit`; params?: Router.UnknownOutputParams; } | { pathname: `/p-import`; params?: Router.UnknownOutputParams; } | { pathname: `/p-photo_detail`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/p-album_home` | `/p-album_home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/p-group_manage` | `/p-group_manage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/p-settings` | `/p-settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/p-ai_edit${`?${string}` | `#${string}` | ''}` | `/p-import${`?${string}` | `#${string}` | ''}` | `/p-photo_detail${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/p-album_home${`?${string}` | `#${string}` | ''}` | `/p-album_home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/p-group_manage${`?${string}` | `#${string}` | ''}` | `/p-group_manage${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/p-settings${`?${string}` | `#${string}` | ''}` | `/p-settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/p-ai_edit`; params?: Router.UnknownInputParams; } | { pathname: `/p-import`; params?: Router.UnknownInputParams; } | { pathname: `/p-photo_detail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/p-album_home` | `/p-album_home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/p-group_manage` | `/p-group_manage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/p-settings` | `/p-settings`; params?: Router.UnknownInputParams; };
    }
  }
}
